config/routes.rb
# config/routes.rb
Rails.application.routes.draw do

  # Root path of the application
  root 'goods#index'

  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Resources for Goods, Categories, Users, Carts, Orders
  resources :goods, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :carts, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end
  resources :orders, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :update, :destroy]
  end

  # Resources for Messages and Chats
  resources :messages, only: [:index, :show, :create]
  resources :chats, only: [:show] do
    resources :messages, only: [:create]
  end

  # WebSocket channel for chat
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :good
  validates :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :goods
  validates :name, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer, class_name: 'User'
  belongs_to :consultant, class_name: 'User'
  has_many :messages, dependent: :destroy
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :category
  has_many :cart_items
  validates :name, :price, :weight, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :content, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates :total_price, presence: true
  validates :status, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :good

  validates :quantity, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :carts
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show edit update destroy]

  def index
    @carts = Cart.all
  end

  def show; end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cart.destroy
    redirect_to carts_url, notice: 'Cart was successfully destroyed.'
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: %i[show edit update destroy]

  def index
    @goods = Good.all
  end

  def show; end

  def new
    @good = Good.new
  end

  def create
    @good = Good.new(good_params)
    if @good.save
      redirect_to @good, notice: 'Good was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @good.update(good_params)
      redirect_to @good, notice: 'Good was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @good.destroy
    redirect_to goods_url, notice: 'Good was successfully destroyed.'
  end

  private

  def set_good
    @good = Good.find(params[:id])
  end

  def good_params
    params.require(:good).permit(:name, :description, :price, :weight, :category_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/messages_helper.rb
module MessagesController
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to 'Show', category_path(category), class: 'btn btn-info' %>
        <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>